# .github/labels.yml
- name: '🌀 chore'
  color: 'BFD4F2'
  description: '기타 수정사항'
- name: '✨ feature'
  color: 'A2E57B'
  description: 'UI, 기능 구현'
- name: '🛠️ fix'
  color: 'E3E3E3'
  description: '작은 수정/핫픽스'
- name: '🐞 bug'
  color: 'E5534B'
  description: "Something isn't working"
- name: '♻️ refactor'
  color: '9D7BF2'
  description: '코드 리팩토링'
- name: '☀️ enhancement'
  color: '61DAFB'
  description: '성능/개선'
- name: '⁉️ question'
  color: 'F9D65C'
  description: '문의사항'
