name: Dev Env (Start/Stop/Restart/Deploy)

on:
  workflow_dispatch:
    inputs:
      cmd:
        description: 'start | stop | restart | deploy'
        required: true
        default: 'start'

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Control Dev Server via SSH
        env:
          NEXT_PUBLIC_API_URL_DEV: ${{ secrets.NEXT_PUBLIC_API_URL_DEV }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY_REPLAY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_REPLAY_DSN }}
          NEXT_PUBLIC_CLARITY_ID: ${{ secrets.NEXT_PUBLIC_CLARITY_ID }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          NEXT_PUBLIC_S3_DOMAIN: ${{ secrets.NEXT_PUBLIC_S3_DOMAIN_DEV }}

        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: NEXT_PUBLIC_API_URL_DEV,NEXT_PUBLIC_SENTRY_DSN,NEXT_PUBLIC_SENTRY_REPLAY_DSN,NEXT_PUBLIC_CLARITY_ID,NEXTAUTH_SECRET,DISCORD_WEBHOOK_URL,NEXT_PUBLIC_S3_DOMAIN
          script: |
            set -e

            APP_DIR="/home/ubuntu/mokkoji-fe-dev"
            BRANCH="dev"
            APP_NAME="mokkoji-dev"
            PORT=3001

            echo "🟢 Command: ${{ github.event.inputs.cmd }}"
            CMD="${{ github.event.inputs.cmd }}"

            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"

            # ✅ START
            if [ "$CMD" = "start" ]; then
              echo "🚀 Starting Dev Server..."
              cd "$APP_DIR"
              git fetch --all
              git checkout "$BRANCH"
              git pull --ff-only

              echo "📝 Writing .env.local..."
              ENV_FILE="$APP_DIR/.env.local"
              rm -f "$ENV_FILE"
              touch "$ENV_FILE"
              echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL_DEV" >> "$ENV_FILE"
              echo "NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN" >> "$ENV_FILE"
              echo "NEXT_PUBLIC_SENTRY_REPLAY_DSN=$NEXT_PUBLIC_SENTRY_REPLAY_DSN" >> "$ENV_FILE"
              echo "NEXT_PUBLIC_CLARITY_ID=$NEXT_PUBLIC_CLARITY_ID" >> "$ENV_FILE"
              echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> "$ENV_FILE"
              echo "DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL" >> "$ENV_FILE"
              echo "NEXT_PUBLIC_S3_DOMAIN=$NEXT_PUBLIC_S3_DOMAIN" >> "$ENV_FILE"

              pnpm install --frozen-lockfile --prefer-offline
              pnpm build

              pm2 describe "$APP_NAME" >/dev/null 2>&1 || \
                pm2 start "pnpm exec next start -p $PORT" \
                  --name "$APP_NAME" \
                  --cwd "$APP_DIR"

              pm2 save
              echo "✅ Dev server started (port $PORT)"

            # ✅ STOP
            elif [ "$CMD" = "stop" ]; then
              echo "🛑 Stopping Dev Server..."
              pm2 stop "$APP_NAME" || true
              pm2 delete "$APP_NAME" || true
              pm2 save || true
              echo "✅ Dev server stopped."

            # ✅ RESTART
            elif [ "$CMD" = "restart" ]; then
              echo "🔁 Restarting Dev Server..."
              pm2 restart "$APP_NAME" || {
                echo "⚠️ Not running, starting new process..."
                pm2 start "pnpm exec next start -p $PORT" \
                  --name "$APP_NAME" \
                  --cwd "$APP_DIR"
              }
              pm2 save
              echo "✅ Dev server restarted."

            # ✅ DEPLOY
            elif [ "$CMD" = "deploy" ]; then
              echo "📦 Deploying latest dev build..."
              cd "$APP_DIR"
              git fetch --all
              git checkout "$BRANCH"
              git pull --ff-only

              pnpm install --frozen-lockfile --prefer-offline
              pnpm build
              pm2 restart "$APP_NAME" || \
                pm2 start "pnpm exec next start -p $PORT" \
                  --name "$APP_NAME" \
                  --cwd "$APP_DIR"

              pm2 save
              echo "✅ Dev deploy complete (branch=$BRANCH, port=$PORT)"

            else
              echo "❌ Unknown command: $CMD"
              exit 1
            fi
