name: Visual Regression Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      # Storybook 빌드
      - name: Build Storybook
        run: npm run build-storybook

      # Storybook 서버 실행 (백그라운드)
      - name: Start Storybook
        run: npx http-server ./storybook-static -p 6006 &

      # Playwright 설치
      - name: Install Playwright
        run: npx playwright install --with-deps

      # Playwright 테스트 실행
      - name: Run Visual Tests
        run: npx playwright test
